CREATE OR REPLACE TRANSIENT TABLE fact_Stock_History_Group2 (
KEY  varchar(250) PRIMARY KEY,
SYMBOl  VARCHAR(16) REFERENCES AIRFLOW0124.BF_DEV."Company_Profile_backup_G2"(symbol),
DATE  DATE,
OPEN NUMBER(18,8),
HIGH NUMBER(18,8),
LOW  NUMBER(18,8),
CLOSE  NUMBER(18,8),
VOLUME  NUMBER(38,8),
ADJCLOSe  NUMBER(18,8)
)

INSERT INTO fact_Stock_History_Group2 VALUES (select concat(symbol,date)as key,* from US_STOCK_DAILY.DCCM.Stock_History )