MERGE INTO AIRFLOW0124.BF_DEV.DIM_COMPANY_PROFILE_WITH_SYMBOL_GROUP5 AS target
USING (
    SELECT *
    FROM US_STOCK_DAILY.DCCM.COMPANY_PROFILE AS s1
    JOIN US_STOCK_DAILY.DCCM.SYMBOLS AS s2
    ON s1.SYMBOL = s2.SYMBOL and s1.EXCHANGE = s2.EXCHANGE
) AS source
ON target.SYMBOL = source.SYMBOL
WHEN MATCHED THEN
    UPDATE SET
    target.PRICE = source.PRICE,
WHEN NOT MATCHED THEN
    INSERT (ID,SYMBOL,PRICE,BETA,VOLAVG,MKTCAP,LASTDIV,RANGE,CHANGES,COMPANYNAME,EXCHANGE,INDUSTRY,WEBSITE,DESCRIPTION,CEO,SECTOR,DCFDIFF,DCF,NAME)
    VALUES (source.ID,source.SYMBOL,source.PRICE,source.BETA,source.VOLAVG,source.MKTCAP,source.LASTDIV,source.RANGE,source.CHANGES,
            source.COMPANYNAME,source.EXCHANGE,source.INDUSTRY,source.WEBSITE,source.DESCRIPTION,source.CEO,source.SECTOR,source.DCFDIFF,source.DCF,source.NAME); 